# Generated by Django 3.1.4 on 2020-12-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cli', '0002_person_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='photo',
        ),
    ]
